### ISSUE TITLE
document changed output schema

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-docs#9]
Add new and changed one, once implemented: 
- [x] `transport_l` (new, geometalab/osmaxx-frontend#422, PR #37)
- [ ] ~~`coastlines`, `land_polygon`, `water_polygons` (new, no attributes)~~ (tracked in #61)
- [x] `poi_a`/`poi_p`, `pow_a`/`pow_p` (update:)
  - [x] burial grounds (geometalab/osmaxx-frontend#477, PR #36)
  - [x] phone (geometalab/osmaxx-conversion-service#84, PR #52)
- [x] `misc_l`:
  - [x] sanity check (PR #58)
  - [x] update (`transport_l`, geometalab/osmaxx-frontend#422, PR #37)
- [x] `address_p` (#56, PR #57)
- [x] `utility_p` (PRs #59, #60)
- [x] `utility_a` (PRs #59, #60)
- [x] `route_l` (PR #51)

**Comment by das-g** [comment]
@hixi, @sfkeller: What was to be improved or changed for (the documentation of) `route_l`?

If I remember correctly, renaming that layer was rejected at the face-to-face meeting on 2016-03-31 at Polyterrasse of ETHZ. And I don't think we had any output-schema changes or changes to the OSM-tag-to-OSMaxx-output-schema mapping scheduled for that layer, did we?

I've made some (mostly cosmetic) `route_l` documentation changes in PR #51.

**Comment by das-g** [comment]
Let's track documentation of the indirectly OSM-derived layers (for coastline, landmass and sea) separately: #61
